// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcGroentenEnFruit.Data;

#nullable disable

namespace MvcGroentenEnFruit.Migrations
{
    [DbContext(typeof(GFDbContext))]
    [Migration("20251106095930_Fkeys")]
    partial class Fkeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcGroentenEnFruit.Models.AankoopOrder", b =>
                {
                    b.Property<int>("AankoopOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AankoopOrderId"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.HasKey("AankoopOrderId");

                    b.HasIndex("ArtikelId");

                    b.ToTable("AankoopOrders");
                });

            modelBuilder.Entity("MvcGroentenEnFruit.Models.Artikel", b =>
                {
                    b.Property<int>("ArtikelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtikelId"));

                    b.Property<string>("ArtikelNaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ArtikelId");

                    b.ToTable("Artikels");
                });

            modelBuilder.Entity("MvcGroentenEnFruit.Models.VerkoopOrder", b =>
                {
                    b.Property<int>("VerkoopOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerkoopOrderId"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.HasKey("VerkoopOrderId");

                    b.HasIndex("ArtikelId");

                    b.ToTable("VerkoopOrders");
                });

            modelBuilder.Entity("MvcGroentenEnFruit.Models.AankoopOrder", b =>
                {
                    b.HasOne("MvcGroentenEnFruit.Models.Artikel", "Artikel")
                        .WithMany("AankoopOrders")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("MvcGroentenEnFruit.Models.VerkoopOrder", b =>
                {
                    b.HasOne("MvcGroentenEnFruit.Models.Artikel", "Artikel")
                        .WithMany("VerkoopOrders")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("MvcGroentenEnFruit.Models.Artikel", b =>
                {
                    b.Navigation("AankoopOrders");

                    b.Navigation("VerkoopOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
